name: node-gui

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-15]

    steps:
      - name: Install Linux Dependencies
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        shell: bash
        env:
          DISPLAY: ':99.0'
        run: |
          set -e
          npm install
          npm test
          npm publish --dry-run
